apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  env.js: |
    window.RUNTIME_ENV = {
      REACT_APP_SERVERURL: "http://35.193.0.44:8081/app",
      REACT_APP_APPID: "opensign"
    };